### ISSUE TITLE
无法发送告警

### ISSUE THREAD

**Issue by loosky** [n9e/wechat-sender#1]
按照配置正常启动了服务，也在后台设置了im和告警策略，但无法收到告警信息，不知道哪里的原因？谢谢！

**Comment by UlricQin** [comment]
信息太少无法判断...首先要确认页面上历史告警里可以看到确实告警了，然后im字段设置的不是个人微信号，是企业微信里边的个人账号名

**Comment by loosky** [comment]
是的，历史告警里面有告警信息，也设置了发给我管理员。管理员设置的是企业微信的账号，使用命令测试是可以发送成功的。
另外，wechat-sender服务政策，且logs目录下面没有日志输出，所以不知道从哪里可以去判断。

**Comment by loosky** [comment]
> 信息太少无法判断...首先要确认页面上历史告警里可以看到确实告警了，然后im字段设置的不是个人微信号，是企业微信里边的个人账号名

测试了mail-sender，同样的配置，邮件可以正常收到，且logs目录下面INFO.log有内容。
wechat-sender仍然无法收到

**Comment by UlricQin** [comment]
monapi.yml里有个配置，是否打开了im：

```
notify:
  p1: ["im", "mail"]
  p2: ["im", "mail"]
  p3: ["im", "mail"]
```
